import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gradient-to-r to-neutral-950 from-neutral-700 text-neutral-50`}
      >
        <main className="flex flex-col w-2/3 mx-auto">{children}</main>
      </body>
    </html>
  );
}
